---
date: Updated "`r format(Sys.time(), '%d %B %Y')`"
fig_caption: yes
incremental: true
output: html_document

---

# Model Ins and Outs 

The **enaR** package provides multiple functions for reading in models
from different data formats used by ecosystem network scientists. The
details and examples of using each of these can be found in the help
file vignette provided in the package documention. 

## 

read.csv(file='...')

> - read.scor
> - read.enam
> - read.wand
> - read.nea
> - read.EcoNet

## 

**enaR** also provides to functions for creating a new model in R,
  which is primarily organizing the different model attributes (flows,
  input, output, etc.) into a network data object, and for decomposing
  an model that's in a network format into a list that is more
  convenient to access. 

## 

pack(flow, input, respiration, export, output, storage, living)

unpack(x='network object')

## Micro-modeling

The following is an exercise that should convey the basic parts of
creating, entering and analyzing a model using **enaR**.

## Micro-modeling (Exercise 1)

M = {F, z, e, r, X, Living}

1. Draw a network model as a flow diagram with 3 nodes
2. Create objects for each of your model components
3. "Pack" your model into a network object
4. "Unpack" your network and look at the parts
5. Plot
6. Investigate some network metric you're interested in


## Micro-modeling (Solution 1)

```{r ,results='hide'}
library(enaR)
F <- c(0,5,0,
       0,0,1,
       0,0,0)
F <- matrix(F,nrow=3,byrow=TRUE)
z <- c(10,0,0)
e <- c(3,3,3)
r <-c(1,1,1)
X <- c(10,3,1)
liv <- c(TRUE,TRUE,FALSE)
toy <- pack(F,z,e,r,X,liv)
enaFlow(toy)

```

